#!/bin/bash
# Report Agent - Generates Progress Summaries
# Part of Graceweb CEO Management System

REPORT_INTERVAL=1800  # 30 minutes
LOG_FILE="logs/report-agent.log"
SUMMARY_FILE="logs/progress-summary.md"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [REPORT] $1" | tee -a "$LOG_FILE"
}

generate_summary() {
    local date=$(date '+%Y-%m-%d %H:%M')
    local commit_count=$(git rev-list --count main 2>/dev/null || echo "0")
    local last_commit=$(git log -1 --oneline 2>/dev/null | head -c 80 || echo "No commits")
    local pending_specs=$(find specs -name "*.md" -exec grep -L "Completed:" {} \; 2>/dev/null | wc -l || echo "0")
    
    # Count completed specs
    local completed_specs=$(find specs -name "*.md" -exec grep -l "Completed:" {} \; 2>/dev/null | wc -l || echo "0")
    
    # Check image count
    local image_count=$(ls public/images/projects/*.png 2>/dev/null | wc -l || echo "0")
    
    # Generate summary
    cat > "$SUMMARY_FILE" << EOF
# Graceweb Progress Report

**Generated:** $date

---

## 📊 Quick Stats
- **Total Commits:** $commit_count
- **Specs Completed:** $completed_specs
- **Specs Pending:** $pending_specs
- **Images:** $image_count

---

## 🎯 Current Focus
$(cat CEO_MANAGEMENT.md 2>/dev/null | grep -A5 "## Issues Found" || echo "- GitHub Pages setup in progress")

---

## ✅ Recently Completed

EOF

    # Add recent commits
    echo "### Recent Activity" >> "$SUMMARY_FILE"
    echo "" >> "$SUMMARY_FILE"
    git log --oneline -10 2>/dev/null | while IFS= read -r line; do
        echo "- $line" >> "$SUMMARY_FILE"
    done

    echo "" >> "$SUMMARY_FILE"
    echo "---" >> "$SUMMARY_FILE"
    echo "*Generated by Report Agent - Next update in 30 minutes*" >> "$SUMMARY_FILE"
    
    log "Summary generated: $SUMMARY_FILE"
    
    # Output to console
    echo ""
    echo "========================================"
    echo "     GRACEWEB PROGRESS REPORT"
    echo "========================================"
    echo ""
    echo "📊 Stats: $completed_specs specs completed, $pending_specs pending"
    echo "📷 Images: $image_count loaded"
    echo "📝 Last commit: $last_commit"
    echo ""
    echo "📄 Full report: $SUMMARY_FILE"
    echo ""
    echo "========================================"
}

log "========================================"
log "Report Agent Started - Every ${REPORT_INTERVAL} seconds"
log "========================================"

# Generate initial report
generate_summary

# Continuous reporting
while true; do
    sleep $REPORT_INTERVAL
    generate_summary
done
